name: Release

on:
  release:
    types: [published]

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/components
          zip -r loxone.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/components/loxone.zip
          asset_name: loxone.zip
          tag: ${{ github.ref }}
          overwrite: true